name: sigmazero
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - entrypoints=0.4
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=1.1.1
  - pip=23.3.1
  - python=3.11.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - chess==1.10.0
    - numpy==1.26.4
    - pandas==2.2.2
    - tqdm
    - streamlit==1.33.0
    - torch==2.2.2
    - lightning
    - tensorboard